### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a

### ISSUE THREAD

**Issue by farissalman12** [bitbrute/evillimiter#101]
python3 bin/evillimiter
Traceback (most recent call last):
  File "/home/blo/Desktop/evillimiter/bin/evillimiter", line 14, in <module>
    from evillimiter.evillimiter import run # pylint: disable=no-name-in-module
  File "/home/blo/Desktop/evillimiter/evillimiter/evillimiter.py", line 9, in <module>
    import evillimiter.networking.utils as netutils
  File "/home/blo/Desktop/evillimiter/evillimiter/networking/utils.py", line 3, in <module>
    from scapy.all import ARP, sr1 # pylint: disable=no-name-in-module
  File "/usr/lib/python3/dist-packages/scapy/all.py", line 18, in <module>
    from scapy.arch import *
  File "/usr/lib/python3/dist-packages/scapy/arch/__init__.py", line 28, in <module>
    from scapy.arch.bpf.core import get_if_raw_addr
  File "/usr/lib/python3/dist-packages/scapy/arch/bpf/core.py", line 31, in <module>
    LIBC = cdll.LoadLibrary(find_library("libc"))
  File "/usr/lib/python3.9/ctypes/util.py", line 341, in find_library
    _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))
  File "/usr/lib/python3.9/ctypes/util.py", line 147, in _findLib_gcc
    if not _is_elf(file):
  File "/usr/lib/python3.9/ctypes/util.py", line 99, in _is_elf
    with open(filename, 'br') as thefile:
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'

**Comment by farissalman12** [comment]
cd /usr/lib/x86_64-linux-gnu/
ln -s -f libc.a liblibc.a

**Comment by binishjoshi** [comment]
@farissalman12 no such directory: 'x86_64-linux-gnu'
Tried creating the directory, and after ```ln -s -f libc.a liblibc.a```, it showed same error.
