### ISSUE TITLE
Can't run evillimiter ?

### ISSUE THREAD

**Issue by HamzaGbada** [bitbrute/evillimiter#120]
I am using Manjaro Linux after the last update I can't run it anymore. I think the problem is due to python version (3.10). 
Does anyone have a solution!

```
Traceback (most recent call last):
  File "/usr/bin/evillimiter", line 33, in <module>
    sys.exit(load_entry_point('evillimiter==1.5.0', 'console_scripts', 'evillimiter')())
  File "/usr/bin/evillimiter", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for evillimiter
```

**Comment by Balhech** [comment]
hi! No response to this? I have the same problem here!

Thanks!

**Comment by HamzaGbada** [comment]
Yes, there was no response! However, I recently discovered that this issue may be caused by `Python3.10` (I was working on Pycharm and encountered a similar issue when building a virtual environment), so I downgraded `Python3.10` to `Python3.8`, which resolved the problem.

**Comment by Balhech** [comment]
> Yes, there was no response! However, I recently discovered that this issue may be caused by `Python3.10` (I was working on Pycharm and encountered a similar issue when building a virtual environment), so I downgraded `Python3.10` to `Python3.8`, which resolved the problem.

I'll try your option, thanks for your reply!
