### ISSUE TITLE
Pls help

### ISSUE THREAD

**Issue by MatoRV** [bitbrute/evillimiter#122]
When i try to run it the following comes out:

Traceback (most recent call last):
 File "/usr/local/bin/evillimiter", line 33, in <module>
  sys.exit(load_entry_point('evillimiter==1.5.0', 'console_scripts', 'evillimiter'))
 File "/usr/local/bin/evillimiter", line 25, in importlib_load_entry_point
   return next(matches).load()
StopIteration

**Comment by MatoRV** [comment]
Ok, my bad, the problem was python version :p
