### ISSUE TITLE
can't run "evillimiter", Error 13, Permission denied.

### ISSUE THREAD

**Issue by ghost** [bitbrute/evillimiter#124]
I can't run it. It takes error when I run "evillimiter".

$ evillimiter
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/evillimiter", line 33, in <module>
    sys.exit(load_entry_point('evillimiter==1.3.0', 'console_scripts', 'evillimiter')())
  File "/data/data/com.termux/files/usr/bin/evillimiter", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/data/data/com.termux/files/usr/lib/python3.10/importlib/metadata/__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "/data/data/com.termux/files/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/evillimiter-1.3.0-py3.10.egg/evillimiter/evillimiter.py", line 9, in <module>
    import evillimiter.networking.utils as netutils
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/evillimiter-1.3.0-py3.10.egg/evillimiter/networking/utils.py", line 3, in <module>
    from scapy.all import ARP, sr1 # pylint: disable=no-name-in-module
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy-2.4.5-py3.10.egg/scapy/all.py", line 16, in <module>
    from scapy.arch import *
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy-2.4.5-py3.10.egg/scapy/arch/__init__.py", line 135, in <module>
    _set_conf_sockets()  # Apply config
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy-2.4.5-py3.10.egg/scapy/config.py", line 618, in _set_conf_sockets
    conf.ifaces.reload()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy-2.4.5-py3.10.egg/scapy/interfaces.py", line 238, in reload
    self._reload_provs()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy-2.4.5-py3.10.egg/scapy/interfaces.py", line 234, in _reload_provs
    self._load(prov.reload(), prov)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy-2.4.5-py3.10.egg/scapy/interfaces.py", line 53, in reload
    return self.load()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy-2.4.5-py3.10.egg/scapy/arch/linux.py", line 420, in load
    get_if_raw_hwaddr(i, siocgifhwaddr=SIOCGIFHWADDR)[1]
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy-2.4.5-py3.10.egg/scapy/arch/common.py", line 87, in get_if_raw_hwaddr
    get_if(iff, siocgifhwaddr)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/scapy-2.4.5-py3.10.egg/scapy/arch/common.py", line 65, in get_if
    return ioctl(sck, cmd, struct.pack("16s16x", iff.encode("utf8")))
PermissionError: [Errno 13] Permission denied

Please help me, thanks very much.

**Comment by Dathrob** [comment]
try running it in sudo ----> "sudo evillimiter"

**Comment by bitbrute** [comment]
EvilLimiter does not work on Termux.

**Comment by ozzyisgreat** [comment]
try running it with root user privileges

**Comment by ghost** [comment]
> EvilLimiter does not work on Termux.

Ok, thanks very much, and express your update to Termux.
