### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by Balhech** [bitbrute/evillimiter#126]
Hi! I completed the installation with not errors but when i try to lunch it with "sudo evillimiter" it says this:

Traceback (most recent call last):
  File "/usr/bin/evillimiter", line 33, in <module>
    sys.exit(load_entry_point('evillimiter==1.5.0', 'console_scripts', 'evillimiter')())
  File "/usr/bin/evillimiter", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 533, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: evillimiter

Know how to fix this?

Thanks!

**Comment by austrian-oak** [comment]
it happened to me when i forced exit evillimiter and not using "quit" . try uninstalling and then reinstalling
