### ISSUE TITLE
Evillimiter permission denied

### ISSUE THREAD

**Issue by DefinitelyNotANinoSimp** [bitbrute/evillimiter#131]
I was trying to execute evillimiter and this is happened

Traceback (most recent call last):
  File "/usr/local/bin/evillimiter", line 33, in <module>
    sys.exit(load_entry_point('evillimiter==1.5.0', 'console_scripts', 'evillimiter')())
  File "/usr/local/lib/python3.9/dist-packages/evillimiter-1.5.0-py3.9.egg/evillimiter/evillimiter.py", line 167, in run
    args = process_arguments(args)
  File "/usr/local/lib/python3.9/dist-packages/evillimiter-1.5.0-py3.9.egg/evillimiter/evillimiter.py", line 93, in process_arguments
    gateway_mac = netutils.get_mac_by_ip(interface, gateway_ip)
  File "/usr/local/lib/python3.9/dist-packages/evillimiter-1.5.0-py3.9.egg/evillimiter/networking/utils.py", line 43, in get_mac_by_ip
    response = sr1(packet, timeout=3, verbose=0, iface=interface)
  File "/usr/lib/python3/dist-packages/scapy/sendrecv.py", line 536, in sr1
    s = conf.L3socket(promisc=promisc, filter=filter,
  File "/usr/lib/python3/dist-packages/scapy/arch/linux.py", line 398, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))  # noqa: E501
  File "/usr/lib/python3.9/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 13] Permission denied

Please help me

**Comment by rxerium** [comment]
Run the command as 'sudo'

**Comment by DevEzro** [comment]
It didn't work for me, even being in root mode

**Comment by rxerium** [comment]
Are you having the same error?

**Comment by DevEzro** [comment]
Yep, is the same. I followed all steps but is still failing

**Comment by Ifeanyidurham** [comment]
any success? i'm having the exact same issue, I was in a thread where I needed to alter a directory to make the program bypass an error code any time I try to utilize the "analyze" function. But I cannot access the directory, it tells me permission denied.

**Comment by DevEzro** [comment]
@Ifeanyidurham it happened the same to me, but I gave up one I didn't found any solution

**Comment by DevEzro** [comment]
I just realised, are you guys @Ifeanyidurham @DefinitelyNotANinoSimp trying in linux o Android/iOS Termux app? I was here for the second one.

If you're in Linux follow this:
- For both, try to git clone again the repo and do the python install again and then use `sudo evillimiter`.
- For @Ifeanyidurham, if you mean 'analyze function' to scan the hosts, then you must use `sudo scan` in stead of `analyze` 'cause it doesn't exists

**Comment by Ifeanyidurham** [comment]
I was using Ubuntu before downloaded Kali Linux to do the whole process over, installed the gh CLI installed evillimiter tried using analyze (a function apart of a set of commands to be used) and ran into the same exact problem.. tried altering the file and I get permission denied im on the verge of giving in

**Comment by DevEzro** [comment]
@Ifeanyidurham that sounds strange for me. I can only tell you to remove evillimiter and follow the repository installation steps. It's the way it worked for me 😢

**Comment by blaabaaaaa** [comment]
you cannot use address resolution protocol without a network adapter.
