### ISSUE TITLE
error while installing evillimiter

### ISSUE THREAD

**Issue by hamzagh1998** [bitbrute/evillimiter#142]
netifaces.c:1:10: fatal error: Python.h: No such file or directory
    1 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command '/usr/bin/gcc' failed with exit code 1

**Comment by soullessschizo** [comment]
first install python3-dev, it fixed the issue for me.

sudo apt-get install python3-dev

**Comment by Diablox00** [comment]
unning install
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:146: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Traceback (most recent call last):
  File "/home/diablo/github_hacks/wifi_scripts/evillimiter/setup.py", line 78, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1213, in run_command
    super().run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.ensure_finalized()  # finalize before bdist_egg munges install cmd
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 335, in finalize_options
    self.local_index = Environment(self.shadow_path + sys.path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1044, in __init__
    self.scan(search_path)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1077, in scan
    self.add(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1096, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in hashcmp
    self.parsed_version,
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2679, in parsed_version
    self._parsed_version = parse_version(self.version)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.4-py1'
(package: adns)

**Comment by austrian-oak** [comment]
seems like a python3 error, i assume you are "python3 setup.py install" ing it.

**Comment by johncarterofmars** [comment]
I had the same error. I am using the exact instructions included on the front page with sudo. I also have python3-dev installed. On Rasp OS (bookworm). It doesn't seem to like it.

**Comment by smithma84** [comment]
> I had the same error. I am using the exact instructions included on the front page with sudo. I also have python3-dev installed. On Rasp OS (bookworm). It doesn't seem to like it.

@johncarterofmars Also having this issue on the latest Raspbian build since I upgraded from Bullseye. Did you end up finding a solution?

**Comment by DavidsonRafaelK** [comment]
netifaces is a C extension, it needs Python's dev headers to compile, and your system is missing them. Install the dev package for your distro first, then retry:

Debian/Ubuntu:
```
sudo apt install python3-dev gcc
```

Fedora/RHEL:
```
sudo dnf install python3-devel gcc
```

After that pip install . (ideally inside a venv) should build netifaces without the Python.h error.
