### ISSUE TITLE
AttributeError: 'L3PacketSocket' object has no attribute 'ins'

### ISSUE THREAD

**Issue by noah22567** [bitbrute/evillimiter#20]
Traceback (most recent call last):
  File "/usr/local/bin/evillimiter", line 11, in <module>
    load_entry_point('evillimiter==1.2.0', 'console_scripts', 'evillimiter')()
  File "/usr/local/lib/python3.7/dist-packages/evillimiter-1.2.0-py3.7.egg/evillimiter/evillimiter.py", line 167, in run
    args = process_arguments(args)
  File "/usr/local/lib/python3.7/dist-packages/evillimiter-1.2.0-py3.7.egg/evillimiter/evillimiter.py", line 93, in process_arguments
    gateway_mac = netutils.get_mac_by_ip(interface, gateway_ip)
  File "/usr/local/lib/python3.7/dist-packages/evillimiter-1.2.0-py3.7.egg/evillimiter/networking/utils.py", line 43, in get_mac_by_ip
    response = sr1(packet, timeout=3, verbose=0, iface=interface)
  File "/usr/local/lib/python3.7/dist-packages/scapy-2.4.3rc3-py3.7.egg/scapy/sendrecv.py", line 488, in sr1
    nofilter=nofilter, iface=iface)
  File "/usr/local/lib/python3.7/dist-packages/scapy-2.4.3rc3-py3.7.egg/scapy/arch/linux.py", line 450, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))  # noqa: E501
  File "/usr/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
Exception ignored in: <function SuperSocket.__del__ at 0x7ffa9e54f9d8>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/scapy-2.4.3rc3-py3.7.egg/scapy/supersocket.py", line 134, in __del__
    self.close()
  File "/usr/local/lib/python3.7/dist-packages/scapy-2.4.3rc3-py3.7.egg/scapy/arch/linux.py", line 492, in close
    if self.promisc and self.ins:
AttributeError: 'L3PacketSocket' object has no attribute '

Kali linux, python3.7 
this occurs when attempting to start evillimiter

**Comment by bitbrute** [comment]
Are you running Evil Limiter unser Windows WSL or natively on Linux? See #4

If so, checkout Evil Limiter for Windows: https://github.com/bitbrute/evillimiter-windows
