### ISSUE TITLE
ImportError: cannot import name 'shell'

### ISSUE THREAD

**Issue by ashwani95** [bitbrute/evillimiter#22]
Getting the following error : 
**On running command `python3 bin/evillimiter`**

`/usr/lib/python3/dist-packages/pkg_resources.py:1031: UserWarning: /home/ashwani/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "bin/evillimiter", line 14, in <module>
    from evillimiter.evillimiter import run # pylint: disable=no-name-in-module
  File "/home/ashwani/chill/evillimiter/evillimiter/evillimiter.py", line 9, in <module>
    import evillimiter.networking.utils as netutils
  File "/home/ashwani/chill/evillimiter/evillimiter/networking/utils.py", line 5, in <module>
    import evillimiter.console.shell as shell
  File "/home/ashwani/chill/evillimiter/evillimiter/console/shell.py", line 3, in <module>
    from evillimiter.console.io import IO
  File "/home/ashwani/chill/evillimiter/evillimiter/console/io.py", line 4, in <module>
    from . import shell
ImportError: cannot import name 'shell'
`

**Similarly for command `evillimiter`**

`/usr/lib/python3/dist-packages/pkg_resources.py:1031: UserWarning: /home/ashwani/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Traceback (most recent call last):
  File "/usr/local/bin/evillimiter", line 9, in <module>
    load_entry_point('evillimiter==1.2.0', 'console_scripts', 'evillimiter')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/evillimiter-1.2.0-py3.4.egg/evillimiter/evillimiter.py", line 9, in <module>
    import evillimiter.networking.utils as netutils
  File "/usr/local/lib/python3.4/dist-packages/evillimiter-1.2.0-py3.4.egg/evillimiter/networking/utils.py", line 5, in <module>
    import evillimiter.console.shell as shell
  File "/usr/local/lib/python3.4/dist-packages/evillimiter-1.2.0-py3.4.egg/evillimiter/console/shell.py", line 3, in <module>
    from evillimiter.console.io import IO
  File "/usr/local/lib/python3.4/dist-packages/evillimiter-1.2.0-py3.4.egg/evillimiter/console/io.py", line 4, in <module>
    from . import shell
ImportError: cannot import name 'shell'
`

**Comment by bitbrute** [comment]
I'm not able to reproduce your issue.
For anyone else encountering this error: @ashwani95 submitted a [pull request](https://github.com/bitbrute/evillimiter/pull/23) that seemed to work for him.
However, for anyone else it will only cause problems.
