### ISSUE TITLE
iOS and Android App?

### ISSUE THREAD

**Issue by codings9** [bitbrute/evillimiter#27]
Question:
What do you think port or make 
an app for evillimiter-ios and android?

I noticed you got a Windows binary and Linux.

**Comment by bitbrute** [comment]
Good point.
I'm not very experienced in App programming. When I have time I'm going to have a look at it. However, I don't think it's possible on IOS. But like I sad, I'm not sure...

**Comment by codings9** [comment]
This would not work?
https://py2app.readthedocs.io/en/latest/

**Comment by leonardus** [comment]
That tool appears to be for creating macOS applications, not mobile applications.

**Comment by leonardus** [comment]
An evillimiter mobile app would likely have to be written from scratch for the specific platform. Not all of the tools that evillimiter uses under the hood are present on Android and iOS.

**Comment by f1vefour** [comment]
And the device would almost certainly need to be rooted as well. You may be able to get this working on an Android device by using termux, you can install python inside termux but I'm not sure if it would have all the needed modules.

**Comment by CRO-THEHACKER** [comment]
Due to the pkg's I'd say this wouldn't work in MacOS unless you would find an alt pkg to use..

**Comment by extinctsion** [comment]
> Good point.
> I'm not very experienced in App programming. When I have time I'm going to have a look at it. However, I don't think it's possible on IOS. But like I sad, I'm not sure...
> 

Won't the linux tool work in termux in android?

**Comment by leocrawf** [comment]
The easiest thing to do would be to make it into an api that runs on a computer on the local network. Any one could then build apps that connect to the apis and run all the commands from the app gui.

**Comment by chrizator** [comment]
@leocrawf One could also just SSH into the machine running EvilLimiter from a mobile device.

**Comment by leocrawf** [comment]
> @leocrawf One could also just SSH into the machine running EvilLimiter from a mobile device.

Is this something that can be done now?

**Comment by chrizator** [comment]
@leocrawf Sure, setup SSH on your machine (there are lots of YouTube videos on how to do it), download an SSH app for your smartphone and connect to your machine. You can enter commands from your smartphone just like you would if you were in front of it. There are plenty of tutorials.

**Comment by Solom2** [comment]
by bitbrute  ~  limit devices on your network :3
                                    v1.5.0


OK   interface: wlan0
OK   gateway ip: 192.168.1.0
Traceback (most recent call last):
  File "/usr/local/bin/evillimiter", line 33, in <module>
    sys.exit(load_entry_point('evillimiter==1.5.0', 'console_scripts', 'evillimiter')())
  File "/usr/local/lib/python3.10/dist-packages/evillimiter-1.5.0-py3.10.egg/evillimiter/evillimiter.py", line 167, in run
    args = process_arguments(args)
  File "/usr/local/lib/python3.10/dist-packages/evillimiter-1.5.0-py3.10.egg/evillimiter/evillimiter.py", line 93, in process_arguments
    gateway_mac = netutils.get_mac_by_ip(interface, gateway_ip)
  File "/usr/local/lib/python3.10/dist-packages/evillimiter-1.5.0-py3.10.egg/evillimiter/networking/utils.py", line 43, in get_mac_by_ip
    response = sr1(packet, timeout=3, verbose=0, iface=interface)
  File "/usr/lib/python3/dist-packages/scapy/sendrecv.py", line 536, in sr1
    s = conf.L3socket(promisc=promisc, filter=filter,
  File "/usr/lib/python3/dist-packages/scapy/arch/linux.py", line 398, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))  # noqa: E501
  File "/usr/lib/python3.10/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 13] Permission denied
