### ISSUE TITLE
Can not use evillimiter on my machine.

### ISSUE THREAD

**Issue by Anecyal** [bitbrute/evillimiter#32]
I'm baffled by what is going wrong. I use arch on my other laptop and it runs fine, but for some reason evillimiter gives me a qdisc error when running on a different arch installation.
This is running at root, flushing does not help. 
`ERR  qdisc root handle could not be created. maybe flush network settings (--flush).
`

**Comment by bitbrute** [comment]
Can you post the output of the following command (if there is any):
```tc qdisc add dev [YOUR INTERFACE NAME] root handle 1:0 htb)```

Replace ```[YOUR INTERFACE NAME]``` with the actual interface name and execute the command only once.

**Comment by fiwskaiser** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/evillimiter", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'netifaces' distribution was not found and is required by evillimiter

**Comment by bitbrute** [comment]
See #3
