### ISSUE TITLE
Ubuntu Windows Subsystem Linux error

### ISSUE THREAD

**Issue by ihateadmins** [bitbrute/evillimiter#4]
Hello, first of all thank you a lot for this tool! I was searching for this for a long time, because my current load balancing system was bad and this is working great on my Kali Linux Laptop.
BUT i want to run it under a Windows System, so im using the Ubuntu Linux Subsytem in Windows 10.
I have every dependency installed and have successfully run the setup, but when i try to start evillimiter i am getting this error:

OK   interface: wifi0
OK   gateway ip: 192.168.178.1
Traceback (most recent call last):
  File "/usr/local/bin/evillimiter", line 9, in <module>
    load_entry_point('evillimiter==1.1.0', 'console_scripts', 'evillimiter')()
  File "/usr/local/lib/python3.5/dist-packages/evillimiter-1.1.0-py3.5.egg/evillimiter/evillimiter.py", line 159, in run
    args = process_arguments(args)
  File "/usr/local/lib/python3.5/dist-packages/evillimiter-1.1.0-py3.5.egg/evillimiter/evillimiter.py", line 91, in process_arguments
    gateway_mac = netutils.get_mac_by_ip(interface, gateway_ip)
  File "/usr/local/lib/python3.5/dist-packages/evillimiter-1.1.0-py3.5.egg/evillimiter/networking/utils.py", line 43, in get_mac_by_ip
    response = sr1(packet, timeout=3, verbose=0, iface=interface)
  File "/usr/local/lib/python3.5/dist-packages/scapy-2.4.3rc1-py3.5.egg/scapy/sendrecv.py", line 501, in sr1
    s = conf.L3socket(promisc=promisc, filter=filter, nofilter=nofilter, iface=iface)  # noqa: E501
  File "/usr/local/lib/python3.5/dist-packages/scapy-2.4.3rc1-py3.5.egg/scapy/arch/linux.py", line 445, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))  # noqa: E501
  File "/usr/lib/python3.5/socket.py", line 134, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
Exception ignored in: <bound method SuperSocket.__del__ of <scapy.arch.linux.L3PacketSocket object at 0x7f77c86d90b8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/scapy-2.4.3rc1-py3.5.egg/scapy/supersocket.py", line 127, in __del__
    self.close()
  File "/usr/local/lib/python3.5/dist-packages/scapy-2.4.3rc1-py3.5.egg/scapy/arch/linux.py", line 481, in close
    set_promisc(self.ins, self.iface, 0)
AttributeError: 'L3PacketSocket' object has no attribute 'ins'

i couldn't solve it, so it would be really great if you could take a look on it.

I also tried to run evillimiter in a VM with the interface as bridged, but it seems to not function. The bandwith is not effected at all.

Thanks in advance

**Comment by ihateadmins** [comment]
of course running a vm would work, but i was hoping that the subsystem would come in handy...

**Comment by bitbrute** [comment]
If I understood correctly, you have two issues:
1. the error message that you posted when you try to run evillimiter in a Linux subsystem
2. evillimiter will not work when run on a virtual machine, although the network interface is bridged

1.
It seems like [scapy ](https://scapy.net/) - a module used by evillimiter to send network packets - is causing this issue. Somehow a required socket object can not be created. This is most likey caused by the subsystem. Regarding evillimiter, I recommend sticking to a virtual machine.
However, I thought about working on a GUI version of evillimiter for Windows only.

2.
This issue does not seem to be a bug inside evillimiter. I tried it myself and it worked perfectly fine. Maybe double check that the interface is truly bridged.

**Comment by ihateadmins** [comment]
I did retry it and checked the network connection on the Debian VM(VM Ware). It is bridged and the network adapter is my wlan adapter. I don't know why it is not working maybe it's a networking issue. I will try to get a cap of it and take a look on it later

**Comment by Eliyanan** [comment]
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)

**Comment by nabeel08** [comment]
I am getting the same error when running Evil Limiter on WSL

`OK   interface: wifi0
OK   gateway ip: 192.168.0.1
Traceback (most recent call last):
  File "bin/evillimiter", line 15, in <module>
    sys.exit(run())
  File "/home/na-08/evillimiter/evillimiter/evillimiter.py", line 167, in run
    args = process_arguments(args)
  File "/home/na-08/evillimiter/evillimiter/evillimiter.py", line 93, in process_arguments
    gateway_mac = netutils.get_mac_by_ip(interface, gateway_ip)
  File "/home/na-08/evillimiter/evillimiter/networking/utils.py", line 43, in get_mac_by_ip
    response = sr1(packet, timeout=3, verbose=0, iface=interface)
  File "/usr/local/lib/python3.6/dist-packages/scapy-2.4.3-py3.6.egg/scapy/sendrecv.py", line 488, in sr1
    nofilter=nofilter, iface=iface)
  File "/usr/local/lib/python3.6/dist-packages/scapy-2.4.3-py3.6.egg/scapy/arch/linux.py", line 467, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))  # noqa: E501
  File "/usr/lib/python3.6/socket.py", line 144, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol`

How to solve this issue ? is there any workaround for this ?

**Comment by adrielwerlich** [comment]
Hello there devs... I´m also having the same issue.
While running on WSL (Kali_Linux), I´m getting

![image](https://user-images.githubusercontent.com/20656722/63641762-1e70b480-c68a-11e9-8487-51b690c8e6fd.png)

File "bin/evillimiter", line 15, in <module>
    sys.exit(run())
  File "/home/adriel/downloads/limiter/evillimiter/evillimiter/evillimiter.py", line 167, in run
    args = process_arguments(args)
  File "/home/adriel/downloads/limiter/evillimiter/evillimiter/evillimiter.py", line 93, in process_arguments
    gateway_mac = netutils.get_mac_by_ip(interface, gateway_ip)
  File "/home/adriel/downloads/limiter/evillimiter/evillimiter/networking/utils.py", line 43, in get_mac_by_ip
    response = sr1(packet, timeout=3, verbose=0, iface=interface)
  File "/usr/local/lib/python3.7/dist-packages/scapy-2.4.3-py3.7.egg/scapy/sendrecv.py", line 488, in sr1
    nofilter=nofilter, iface=iface)
  File "/usr/local/lib/python3.7/dist-packages/scapy-2.4.3-py3.7.egg/scapy/arch/linux.py", line 467, in __init__
    self.ins = socket.socket(socket.AF_PACKET, socket.SOCK_RAW, socket.htons(type))  # noqa: E501
  File "/usr/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol

Is there any workaround for this?

**Comment by bitbrute** [comment]
WSL will not be supported by this version of EvilLimiter and I will not work on fixing it.
There already is a [Windows GUI version](https://github.com/bitbrute/evillimiter-windows) of the tool.
