### ISSUE TITLE
Getting 'ascii' codec error, possibly created by colorama

### ISSUE THREAD

**Issue by rshopnil** [bitbrute/evillimiter#41]
``Traceback (most recent call last):
  File "/usr/local/bin/evillimiter", line 9, in <module>
    load_entry_point('evillimiter==1.3.0', 'console_scripts', 'evillimiter')()                                                                       
  File "/usr/local/lib/python3.5/dist-packages/evillimiter-1.3.0-py3.5.egg/evillimiter/evillimiter.py", line 157, in run                             
    IO.print(get_main_banner(version))
  File "/usr/local/lib/python3.5/dist-packages/evillimiter-1.3.0-py3.5.egg/evillimiter/console/io.py", line 33, in print                             
    print(text, end=end, flush=flush)
  File "/usr/local/lib/python3.5/dist-packages/colorama/ansitowin32.py", line 41, in write                                                           
    self.__convertor.write(text)
  File "/usr/local/lib/python3.5/dist-packages/colorama/ansitowin32.py", line 164, in write                                                          
    self.wrapped.write(text)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-16: ordinal not in range(128)``

How to solve this. Running project from docker container.

**Comment by rshopnil** [comment]
The problem seems to stem down from issues with **_python ascii encoding_**

Solved it by adding the next line to ``/etc/environment``

``PYTHONIOENCODING=utf8``

If anyone faces the same issue in the future, simply do

``echo PYTHONIOENCODING=utf8 >> /etc/environment``
