### ISSUE TITLE
evil limiter not opening

### ISSUE THREAD

**Issue by farissalman12** [bitbrute/evillimiter#65]
Traceback (most recent call last):
  File "/usr/local/bin/evillimiter", line 11, in <module>
    load_entry_point('evillimiter==1.4.0', 'console_scripts', 'evillimiter')()
  File "/usr/local/lib/python2.7/dist-packages/setuptools-27.3.0.post20200622-py2.7.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/setuptools-27.3.0.post20200622-py2.7.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/setuptools-27.3.0.post20200622-py2.7.egg/pkg_resources/__init__.py", line 2258, in load
  File "/usr/local/lib/python2.7/dist-packages/setuptools-27.3.0.post20200622-py2.7.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/usr/local/lib/python2.7/dist-packages/evillimiter-1.4.0-py2.7.egg/evillimiter/evillimiter.py", line 157
    IO.print(get_main_banner(version))
           ^
SyntaxError: invalid syntax

**Comment by bitbrute** [comment]
You are using ```python2.7``` instead of ```python3```.
