### ISSUE TITLE
AttributeError: module 'netifaces' has no attribute 

### ISSUE THREAD

**Issue by Wegito** [bitbrute/evillimiter#76]
Hi, i'm facing this Problem 
Traceback (most recent call last):
  File "/usr/local/bin/evillimiter", line 33, in <module>
    sys.exit(load_entry_point('evillimiter==1.5.0', 'console_scripts', 'evillimiter')())
  File "/usr/local/lib/python3.8/dist-packages/evillimiter-1.5.0-py3.8.egg/evillimiter/evillimiter.py", line 167, in run
    args = process_arguments(args)
  File "/usr/local/lib/python3.8/dist-packages/evillimiter-1.5.0-py3.8.egg/evillimiter/evillimiter.py", line 70, in process_arguments
    interface = netutils.get_default_interface()
  File "/usr/local/lib/python3.8/dist-packages/evillimiter-1.5.0-py3.8.egg/evillimiter/networking/utils.py", line 13, in get_default_interface
    gateways = netifaces.gateways()
AttributeError: module 'netifaces' has no attribute 'gateways'
i solved the interfaces lost issue, install the netifaces but nothing happend can't improt interfaces/getways

**Comment by bitbrute** [comment]
Did you already try the solution presented in [this issue](https://github.com/bitbrute/evillimiter/issues/69)?

**Comment by Wegito** [comment]
yeah of course it doesn't worked

**Comment by Wegito** [comment]
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    import setuptools
ImportError: No module named setuptools
 why do this Error appears ?

**Comment by Wegito** [comment]
nvm i solved it :)

**Comment by xiddigaduula** [comment]
please @help am having these
Traceback (most recent call last):
  File "/home/xiddigaduula/Desktop/evillimiter/bin/evillimiter", line 14, in <module>
    from evillimiter.evillimiter import run # pylint: disable=no-name-in-module
  File "/home/xiddigaduula/Desktop/evillimiter/evillimiter/evillimiter.py", line 9, in <module>
    import evillimiter.networking.utils as netutils
  File "/home/xiddigaduula/Desktop/evillimiter/evillimiter/networking/utils.py", line 2, in <module>
    import netifaces
ModuleNotFoundError: No module named 'netifaces'

**Comment by elhananjair** [comment]
> nvm i solved it :)

How?
