### ISSUE TITLE
EVILLIMITER Installing won't work on kali linux (WSL2)

### ISSUE THREAD

**Issue by xiddigaduula** [bitbrute/evillimiter#77]
i can't install evillimiter 
code: sudo python3 setup.py  install
and i getting this
ofcourse and i installed python
please help i really want this to use

Traceback (most recent call last):
  File "/home/xiddigaduula/Desktop/evillimiter/bin/evillimiter", line 14, in <module>
    from evillimiter.evillimiter import run # pylint: disable=no-name-in-module
  File "/home/xiddigaduula/Desktop/evillimiter/evillimiter/evillimiter.py", line 9, in <module>
    import evillimiter.networking.utils as netutils
  File "/home/xiddigaduula/Desktop/evillimiter/evillimiter/networking/utils.py", line 2, in <module>
    import netifaces
ModuleNotFoundError: No module named 'netifaces'

![Screenshot_2020-11-06_14_12_01](https://user-images.githubusercontent.com/74133505/98461393-c81f6100-21bc-11eb-9bf0-af56086e22c9.png)

**Comment by xiddigaduula** [comment]
> i can't install evillimiter
> code: sudo python3 setup.py install
> and i getting this
> ofcourse and i installed python
> please help i really want this to use
> 
> Traceback (most recent call last):
> File "/home/xiddigaduula/Desktop/evillimiter/bin/evillimiter", line 14, in
> from evillimiter.evillimiter import run # pylint: disable=no-name-in-module
> File "/home/xiddigaduula/Desktop/evillimiter/evillimiter/evillimiter.py", line 9, in
> import evillimiter.networking.utils as netutils
> File "/home/xiddigaduula/Desktop/evillimiter/evillimiter/networking/utils.py", line 2, in
> import netifaces
> ModuleNotFoundError: No module named 'netifaces'
> 
> ![Screenshot_2020-11-06_14_12_01](https://user-images.githubusercontent.com/74133505/98461393-c81f6100-21bc-11eb-9bf0-af56086e22c9.png)

am noob please help me
