### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by iJustGhost** [bitbrute/evillimiter#79]
I've successfully installed before in Termux without any issue and I tried to install it again but I got this error.

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/evillimiter", line 33, in <module>
    sys.exit(load_entry_point('evillimiter==1.5.0', 'console_scripts', 'evillimiter')())
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/evillimiter-1.5.0-py3.9.egg/evillimiter/evillimiter.py", line 167, in run                         args = process_arguments(args)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/evillimiter-1.5.0-py3.9.egg/evillimiter/evillimiter.py", line 70, in process_arguments
    interface = netutils.get_default_interface()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/evillimiter-1.5.0-py3.9.egg/evillimiter/networking/utils.py", line 13, in get_default_interface
    gateways = netifaces.gateways()                                              AttributeError: module 'netifaces' has no attribute 'gateways'

Ps I have rooted device.

**Comment by iJustGhost** [comment]
Oops looks like this is already solved...
