### ISSUE TITLE
Program wont launch anymore - Kali 2020.3

### ISSUE THREAD

**Issue by ghost** [bitbrute/evillimiter#88]
I had no issues until today.  

Any fixes?

Traceback (most recent call last):
  File "/usr/local/bin/evillimiter", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3259, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3242, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3271, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'evillimiter==1.5.0' distribution was not found and is required by the application

**Comment by ghost** [comment]
Issue resolved.   

cd /usr/lib/x86_64-linux-gnu/
sudo ln -s -f libc.a liblibc.a
